config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources "arts" do
    resources "coms"
  end
  root "arts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  has_many :coms, dependent: :destroy
  validates :name, presence: true, length: { minimum: 6 }
  validates :lastname, presence: true
end

app/models/com.rb
class Com < ApplicationRecord
  belongs_to :art
  validates :com, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @arts = Art.all
  end

  def show
    @art = Art.find(params[:id])
  end

  def new
    @art = Art.new
  end

  def create
    @art = Art.new(art_params)
    if @art.save
      redirect_to @art
    else
      render 'new'
    end
  end

  def edit
    @art = Art.find(params[:id])
  end

  def update
    @art = Art.find(params[:id])
    if @art.update(art_params)
      redirect_to @art
    else
      render 'edit'
    end
  end

  def destroy
    @art = Art.find(params[:id])
    @art.destroy
    redirect_to @art
  end

  private
  def art_params
    params.require(:art).permit(:name, :lastname)
  end
end

app/controllers/coms_controller.rb
class ComsController < ApplicationController

  def create
    @art = Art.find(params[:art_id])
    @com = @art.coms.create(com_params)
    redirect_to art_path(@art)
  end

  def destroy
    @art = Art.find(params[:art_id])
    @com = @art.coms.find(params[:id])
    @com.destroy
    redirect_to art_path(@art)
  end

  private 
  def com_params
    params.require(:com).permit(:com, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/views/arts/_form.html.erb
<%= form_with model: @art, local: true do |form| %>
 
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@art.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @art.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<h1>Listing Table</h1>
<%= link_to 'New', new_art_path %><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @arts.each do |art| %>
    <tr>
      <td><%= art.name %></td>
      <td><%= art.lastname %></td>
      <td><%= link_to 'Show', art_path(art) %></td>
      <td><%= link_to 'Edit', edit_art_path(art) %></td>
      <td><%= link_to 'Delete', art_path(art), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @art.name %>
</p>
 
<p>
  <strong>Lastname:</strong>
  <%= @art.lastname %>
</p>

<h2>Commenter</h2>
<%= render @art.coms %>

<h2>Add a comment</h2>
<%= render 'coms/form' %>
 
<%= link_to 'Back', arts_path %>

app/views/coms/_com.html.erb
<p>
  <strong>Comment:</strong>
  <%= com.com %>
</p>
 
<p>
  <strong>Message:</strong>
  <%= com.message %>
</p>

<p>
  <%= link_to 'Destroy Comment', [com.art, com],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/coms/_form.html.erb
<%= form_with(model: [ @art, @art.coms.build ], local: true) do |form| %>
<p>
    <%= form.label :com %><br>
    <%= form.text_field :com %>
  </p>
  <p>
    <%= form.label :message %><br>
    <%= form.text_field :message %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fouthtest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>